apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-petclinic-<YOUR_PROD_PROJECT> # (Ex: quarkus-petclinic-user0-prod)
spec:
  destination:
    namespace: <YOUR_PROD_PROJECT> # (Ex: user0-prod)
    name: in-cluster
  project: <YOUR_ARGOCD_PROJECT> # (Ex: user0)
  source:
    path: production
    repoURL: 'https://github.com/<YOUR_GITHUB_ORG>/petclinic-config.git'
    targetRevision: simple